@startuml context
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(client, "Клиент банка", "Клиент банка, заинтересованный в открытии депозита")
Person(manager_cc, "Сотрудник кол-центра", "Сотрудник компании, который обрабатывает заявки")
Person(manager_bo_d, "Сотрудник бэк-офиса депозитов", "Сотрудник компании, который обрабатывает заявки и ставки по депозитам")
Person(manager_bo_c, "Сотрудник бэк-офиса кредитов", "Сотрудник компании, который обрабатывает ставки по депозитам")

System_Boundary(bank, "Банк-стандарт"){
    System(depositSystem, "Система онлайн обработки открытия депозитов", "Система, которая позволяет пользователю открывать депозиты онлайн")
    System(abs, "АБС", "Система, которая позволяет управлять депозитами и ставками")
    System(cc, "Кол-центр", "Система, которая позволяет обрабатывать обращения клиентов")
}
System_Ext(telecom, "Телеком-оператор", "Внешний оператор по отправке СМС")

Rel_D(depositSystem, telecom, "Отправка СМС-оповещений клиенту")
Rel(telecom, client, "СМС-оповещение")
Rel(client, depositSystem, "Оформление заявки на открытие депозита", "Интернет-банк, сайт")
Rel_R(depositSystem, cc, "Регистрация заявки от неавторизованного пользователя")
Rel_L(depositSystem, abs, "Регистрация заявки от авторизованного пользователя")
Rel(manager_cc, cc, "Обработка обращений в КЦ")
Rel(manager_bo_d, abs, "Формирование ставок по депозиту, обработка заявок на открытие депозита")
Rel(manager_bo_c, abs, "Формирование ставок по депозиту")


@enduml 