@startuml context
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(client, "Клиент банка", "Клиент банка, заинтересованный в открытии депозита")
Person(manager_cc, "Сотрудник кол-центра", "Сотрудник компании, который обрабатывает заявки")
Person_Ext(manager_cc_ext, "Сотрудник партнёрского кол-центра", "Сотрудник партнёрского кол-центра, который обрабатывает заявки")
Person(manager_bo_d, "Сотрудник бэк-офиса депозитов", "Сотрудник компании, который обрабатывает ставки по депозитам")
Person(manager_bo_c, "Сотрудник бэк-офиса кредитов", "Сотрудник компании, который обрабатывает ставки по депозитам")

System_Boundary(bank, "Банк-стандарт"){
    System(depositSystem, "Система онлайн обработки открытия депозитов", "Система, которая позволяет пользователю открывать депозиты онлайн")
    System(abs, "АБС", "Система, которая позволяет управлять депозитами и ставками")
    System(cc, "Кол-центр", "Система, которая позволяет обрабатывать обращения клиентов")
}
System_Ext(cc_ext, "Система партнёрского кол-центра", "Система, которая позволяет обрабатывать обращения клиентов")

Rel_R(depositSystem, cc, "Передача ставок по депозиту")
Rel_L(depositSystem, cc_ext, "Передача ставок по депозиту")
Rel_D(depositSystem, abs, "Получение ставок по депозиту")
Rel_R(manager_cc, cc, "Обработка обращений в КЦ")
Rel(manager_cc_ext, cc_ext, "Обработка обращений в КЦ")
Rel_U(manager_bo_d, abs, "Формирование ставок по депозиту")
Rel_U(manager_bo_c, abs, "Формирование ставок по депозиту")
Rel_U(manager_cc, client, "Взаимодействие с клиентом")
Rel_U(manager_cc_ext, client, "Взаимодействие с клиентом")
Lay_R(manager_cc_ext, manager_cc)

@enduml 